# Generated by Django 2.1 on 2018-08-19 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=17)),
                ('date_published', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BookWish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_wished', models.DateTimeField(verbose_name=True)),
                ('date_granted', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishlist.Book')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=80)),
                ('token', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='bookwish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishlist.User'),
        ),
    ]
